### ISSUE TITLE
TableView Scrolling

### ISSUE THREAD

**Issue by f33chobits** [nicklockwood/SwipeView#148]
Hi Nick~
   I'm currently using three tableviews in swipeview, but they scroll syncronously. When the swipeview is being dragged and move up/down, the tableview in the swipeview still received touches. How could I prevent it?
   Also when the tableview is draing up/down, the swipeview could also receive left/right drag, how could I prevent it either?

**Comment by eytanbiala** [comment]
@f33chobits  Were you able to come up with a solution for this? I'd be interested in seeing how it works.

**Comment by f33chobits** [comment]
Not needed. This problem comes up because DZNEmptyDataSet. It's been fixed already, but haven't been posted to cocoapods yet. You can look into the DZNEmptyDataSet issues.
