### ISSUE TITLE
Vertical alignment SwipeView items

### ISSUE THREAD

**Issue by ArturBaghdas** [nicklockwood/SwipeView#182]
Is there a possibility to vertical align the items ?

**Comment by nicklockwood** [comment]
Yes, use the alignment property.

**Comment by ArturBaghdas** [comment]
I mean vertical alignment of horizontal items. Now it's always center. See attached screenshot. Thanks
![img_4938](https://cloud.githubusercontent.com/assets/13787379/10449962/9f41d056-719f-11e5-8a7b-cd8087ee5bf6.PNG)

**Comment by nicklockwood** [comment]
Oh, I see. There's no property for that, but you could either make your SwipeView smaller so it doesn't fill the height of the screen, or you can place each itemView inside another view and position them at the top.

**Comment by ArturBaghdas** [comment]
Ok thank you, but the thing is that I want to swipe items within all screen but the items should be aligned to the top.
