### ISSUE TITLE
Animate views to be of a different size as you scroll (zooming in/out animation)

### ISSUE THREAD

**Issue by jyounus** [nicklockwood/SwipeView#187]
Hey there,

Anyone got any ideas if I can achieve this result with this library? If anyone has already done this and could share their work, it would be much appreciated!

Here's a gif of what I'm trying to achieve:
http://i.stack.imgur.com/aXzEB.gif

**Comment by khuong291** [comment]
In this case, you should use Carousel library to do this instead of this library

**Comment by nicklockwood** [comment]
I think @khuong291 means my iCarousel library: https://github.com/nicklockwood/iCarousel

It has essentially the same API as SwipeView, but supports arbitrary 3D transforms for the carousel views.
