### ISSUE TITLE
Use of NSInteger instead of NSUInteger

### ISSUE THREAD

**Issue by oliland** [nicklockwood/SwipeView#21]
Many methods (such as `- currentItemIndex`) return an NSInteger as opposed to an NSUInteger, which seems strange as most cocoa collections use NSUInteger so I have to typecast a lot. Is there a reason for this?

**Comment by colasbd** [comment]
There is even more crazy than that!

``` obj-c
NSUInteger index = 0;
BOOL b = (index > -1);
```

Guess what is `b` value...
